# Generated by Django 5.2.16 on 2026-07-13 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0004_seed_demo_projects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32, unique=True, verbose_name='版本')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('rules', models.JSONField(default=dict, verbose_name='评分规则')),
                ('is_active', models.BooleanField(default=True, verbose_name='当前启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='diagnosisversion',
            name='confirmation_mode',
            field=models.CharField(default='manual', max_length=32, verbose_name='确认方式'),
        ),
        migrations.AddField(
            model_name='diagnosisversion',
            name='scoring_standard_version',
            field=models.CharField(default='pdp-v1', max_length=32, verbose_name='评分标准版本'),
        ),
        migrations.AddField(
            model_name='diagnosisversion',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_versions', to='diagnosis.pdpsource'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdp_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DiagnosisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='queued', max_length=32, verbose_name='状态')),
                ('stage', models.CharField(default='queued', max_length=32, verbose_name='阶段')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='进度')),
                ('adapter', models.CharField(default='mock', max_length=64, verbose_name='模型适配器')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='模型名称')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='诊断上下文')),
                ('error_code', models.CharField(blank=True, max_length=64, verbose_name='错误代码')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_jobs', to=settings.AUTH_USER_MODEL)),
                ('locked_version', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_job', to='diagnosis.diagnosisversion')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_jobs', to='diagnosis.project')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_jobs', to='diagnosis.pdpsource')),
                ('scoring_standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosis_jobs', to='diagnosis.scoringstandard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64, verbose_name='供应商')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型')),
                ('prompt_version', models.CharField(default='pdp-score-v1', max_length=64, verbose_name='提示词版本')),
                ('status', models.CharField(default='running', max_length=32, verbose_name='状态')),
                ('request_id', models.CharField(blank=True, max_length=128, verbose_name='请求 ID')),
                ('usage', models.JSONField(blank=True, default=dict, verbose_name='用量')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='耗时毫秒')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_runs', to='diagnosis.diagnosisjob')),
            ],
        ),
        migrations.CreateModel(
            name='PageEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=64, verbose_name='模块编码')),
                ('page_index', models.PositiveIntegerField(default=0, verbose_name='页码')),
                ('bbox', models.JSONField(blank=True, default=dict, verbose_name='页面坐标')),
                ('evidence_type', models.CharField(default='page_region', max_length=32, verbose_name='证据类型')),
                ('ocr_text', models.TextField(blank=True, verbose_name='识别文字')),
                ('crop_image', models.FileField(blank=True, upload_to='pdp_evidence/%Y/%m/', verbose_name='证据截图')),
                ('model_reason', models.TextField(blank=True, verbose_name='模型解释')),
                ('confidence', models.DecimalField(decimal_places=3, default=0, max_digits=4, verbose_name='置信度')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='diagnosis.diagnosisjob')),
            ],
            options={
                'ordering': ['module_code', 'page_index'],
            },
        ),
        migrations.CreateModel(
            name='ModuleAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=64, verbose_name='模块编码')),
                ('module_name', models.CharField(max_length=100, verbose_name='模块名称')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='权重')),
                ('coefficient', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='评分系数')),
                ('score', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='得分')),
                ('maturity', models.CharField(max_length=8, verbose_name='成熟度')),
                ('judgment', models.TextField(verbose_name='判断')),
                ('confidence', models.DecimalField(decimal_places=3, default=0, max_digits=4, verbose_name='置信度')),
                ('auto_confirmed', models.BooleanField(default=True, verbose_name='AI 自动确认')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='diagnosis.diagnosisjob')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('job', 'module_code'), name='unique_job_module_assessment')],
            },
        ),
    ]
