# Generated by Django 5.2.16 on 2026-07-13 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0007_link_scoring_standard_to_skill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='PDP Lab 默认集成', max_length=100, verbose_name='配置名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='当前启用')),
                ('ai_adapter', models.CharField(choices=[('auto', '自动选择'), ('openai', 'OpenAI'), ('mock', 'Mock 验证')], default='auto', max_length=32, verbose_name='AI 适配器')),
                ('ai_model_name', models.CharField(default='gpt-5.4-mini', max_length=100, verbose_name='AI 模型')),
                ('ai_base_url', models.URLField(blank=True, help_text='留空使用 OpenAI 官方地址', verbose_name='API Base URL')),
                ('ai_timeout_seconds', models.PositiveIntegerField(default=180, verbose_name='API 超时（秒）')),
                ('api_key_ciphertext', models.TextField(blank=True, editable=False, verbose_name='加密 API Key')),
                ('skill_name', models.CharField(default='pdp-detail-page-methodology', max_length=120, verbose_name='Skill 名称')),
                ('skill_mode', models.CharField(choices=[('built_in', '内置版本化规则'), ('remote_http', '远程 HTTP Skill')], default='built_in', max_length=32, verbose_name='Skill 接入方式')),
                ('skill_endpoint_url', models.URLField(blank=True, help_text='例如 http://127.0.0.1:8765/v1/skills/pdp-detail-page-methodology/rules', verbose_name='Skill 接入地址 / 端口')),
                ('skill_timeout_seconds', models.PositiveIntegerField(default=30, verbose_name='Skill 超时（秒）')),
                ('skill_token_ciphertext', models.TextField(blank=True, editable=False, verbose_name='Skill 加密 Token')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': 'AI 模型与 Skill 接入设置',
                'verbose_name_plural': 'AI 模型与 Skill 接入设置',
            },
        ),
    ]
