PDP_V5_RULES = {
    "version": "pdp-v5",
    "source_skill": "pdp-detail-page-methodology",
    "source_mode": "versioned_runtime_rules",
    "source_revision": "sha256:88b13f5890ee520c162a90c30eee59c3c5ff55b7336b38eb4e5a92d0ce1e8a7d",
    "skill_manifest_revision": "sha256:88b13f5890ee520c162a90c30eee59c3c5ff55b7336b38eb4e5a92d0ce1e8a7d",
    "coefficients": {"弱": 0, "较弱": 0.25, "中": 0.5, "强": 0.75, "极强": 1},
    "maturity_definitions": {
        "弱": "无有效模块；标题、占位、通用模板、装饰素材或空壳不计入模块存在",
        "较弱": "有产品相关内容，但只有文案、单一信息、T2 视觉或棚拍/模特图，信息与视觉尚未形成有效结合",
        "中": "产品信息与 T2 级视觉形成基本结合，能够回答基础购买问题，但证据、吸引力或叙事仍不完整",
        "强": "完整匹配的信息内容与 T1 级视觉有效结合，层级清楚并能辅助购买决策",
        "极强": "完整可信的信息、证据与 T0 级视觉高度结合，形成品牌记忆、专业说服与标杆增长表达",
    },
    "judgment_order": ["有效存在性", "信息完整度", "T2/T1/T0 视觉层级", "信息与视觉匹配度", "消费者购买决策价值"],
    "visual_tier_rules": {
        "t2_max_coefficient": 0.5,
        "t1_max_coefficient": 0.75,
        "t0_requires_complete_matched_evidence": True,
        "t0_eligible_evidence": [
            "designed_model_product_composite",
            "pagewide_designed_model_product_sequence",
            "product_3d_structure_explanation",
            "product_specific_art_illustration",
        ],
        "t1_only_evidence": ["designed_model_only", "designed_product_only"],
    },
    "modules": [
        {"code": "product_kv", "name": "产品KV/封面故事", "weight": 10, "strong_standard": "0.5-1屏内讲清产品主张、系列定位、核心卖点和主视觉"},
        {"code": "scenario", "name": "沉浸式购物/场景化", "weight": 18, "strong_standard": "场景覆盖真实使用、穿搭、运动状态和情绪代入"},
        {"code": "selling_point_proof", "name": "卖点与功能证明", "weight": 14, "strong_standard": "核心卖点排序清楚，有技术、材料、对比或使用证据"},
        {"code": "interactive_content", "name": "产品互动/动态内容", "weight": 8, "strong_standard": "视频、AR、3D或动效直接解释功能、结构或试穿效果"},
        {"code": "detail_review", "name": "细节查阅", "weight": 12, "strong_standard": "多角度、颜色、材质、结构、局部细节完整"},
        {"code": "fit_comparison", "name": "尺码/适配与对比选购", "weight": 10, "strong_standard": "测量方式、脚型/身型、版型建议、消费者荐言、系列对比完整"},
        {"code": "basic_information", "name": "基础信息", "weight": 8, "strong_standard": "面料、材质、成分、颜色、货号、规格结构化呈现"},
        {"code": "service", "name": "使用说明/服务事项", "weight": 5, "strong_standard": "服务、护理、退换、售后能降低购买顾虑"},
        {"code": "recommendation", "name": "关联推荐/延展购买", "weight": 5, "strong_standard": "推荐基于系列、场景、穿搭、用户意图"},
        {"code": "endorsement", "name": "品牌/产品背书", "weight": 5, "strong_standard": "有认证、奖项、机构、科技来源、用户口碑或品牌资产"},
        {"code": "page_rhythm", "name": "页面结构与节奏", "weight": 5, "strong_standard": "封面-沉浸-卖点-细节-信息-服务-推荐-背书形成购买叙事"},
    ],
    "star_bands": [
        {"lt": 10, "rating": 1, "page_type": "严重信息缺失页", "business_meaning": "几乎无法转化"},
        {"lt": 20, "rating": 1.5, "page_type": "信息缺失页", "business_meaning": "很难转化"},
        {"lt": 27.5, "rating": 2, "page_type": "基础陈列页", "business_meaning": "只能展示商品"},
        {"lt": 35, "rating": 2.5, "page_type": "基础陈列增强页", "business_meaning": "商品展示更完整，但决策支持弱"},
        {"lt": 42.5, "rating": 3, "page_type": "基础说明页", "business_meaning": "能看懂，但说服弱"},
        {"lt": 50, "rating": 3.5, "page_type": "基础说明增强页", "business_meaning": "信息更完整，但证据和视觉吸引不足"},
        {"lt": 57.5, "rating": 4, "page_type": "完整说明页", "business_meaning": "基本完整，但转化阻力多"},
        {"lt": 65, "rating": 4.5, "page_type": "完整说明增强页", "business_meaning": "接近成熟转化，但关键模块仍偏中"},
        {"lt": 72.5, "rating": 5, "page_type": "成熟转化页", "business_meaning": "能支撑大多数用户决策"},
        {"lt": 80, "rating": 5.5, "page_type": "成熟转化增强页", "business_meaning": "转化链路成熟，少数专业证据仍待补强"},
        {"lt": 85, "rating": 6, "page_type": "专业决策页", "business_meaning": "有强证据、强场景、强信任"},
        {"lt": 90, "rating": 6.5, "page_type": "专业决策增强页", "business_meaning": "专业证据充分，接近标杆增长"},
        {"lt": 101, "rating": 7, "page_type": "标杆增长页", "business_meaning": "形成品牌级内容资产"},
    ],
}
